whitelist_rules:
    - attributes
    - class_delegate_protocol
    - closing_brace
    - closure_end_indentation
    - closure_spacing
    - colon
    - comma
    - cyclomatic_complexity
    - empty_count
    - empty_parameters
    - empty_parentheses_with_trailing_closure
    - explicit_init
    - first_where
    - force_cast
    - force_try
    - force_unwrapping
    - implicitly_unwrapped_optional
    - implicit_getter
    - leading_whitespace
    - legacy_cggeometry_functions
    - legacy_constant
    - legacy_constructor
    - legacy_nsgeometry_functions
    - opening_brace
    - operator_usage_whitespace
    - redundant_discardable_let
    - redundant_nil_coalescing
    - redundant_void_return
    - return_arrow_whitespace
    - shorthand_operator
    - statement_position
    - syntactic_sugar
    - trailing_comma
    - trailing_newline
    - trailing_semicolon
    - trailing_whitespace
    - vertical_whitespace
    - void_return
    - weak_delegate
    - custom_rules
    - todo
    - closure_parameter_position
    - collection_alignment
    - conditional_returns_on_newline
    - control_statement
    - convenience_type
    - discouraged_optional_boolean
    - empty_string
    - function_parameter_count
    - inert_defer
    - mark
    - toggle_bool
    - trailing_closure
    - unused_import
    - unused_optional_binding

    # - missing_docs 

    # logic
# disabled_rules: # rule identifiers to exclude from running
#   - leading_whitespace
#   - line_length
#   - variable_name
#   - file_length
#   - missing_docs

#   - force_cast
#   - force_try
#   - force_unwrapping

#   #
opt_in_rules: # some rules are only opt-in
  # - opening_brace
  # - closure_spacing
  # - colon
  # - comma
  # - conditional_returns_on_newline
  # - control_statement
  # - legacy_cggeometry_functions
  # - legacy_constant
  # - legacy_constructor
  # - mark
  # - overridden_super_call
  # - return_arrow_whitespace
  # - statement_position
  # - trailing_newline
  # - trailing_semicolon
  # - trailing_whitespace
  # - vertical_whitespace
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - fastlane
  - Pods
  - .bundle

custom_rules:
  image_name_initialization: # Disable UIImage init from name
      included: ".*.swift"
      name: "Image initialization"
      regex: 'UIImage\(named:[^)]+\)'
      message: "Use UIImage(assetName: ) instead"
      severity: error

  realm_in_ui:
      included: "Screens/.*.swift|User Stories/.*.swift"
      name: "Realm can be used only in services"
      regex: "Realm"
      message: "Realm can be used only in serivces"
      severity: error

  disclosure_of_view_details:
    included: ".*ViewOutput.swift|.*ViewInput.swift"
    name: "Details opening in View protocols"
    regex: "cell|Cell|button|Button|Table|tableView"
    message: "The disclosure of details the implementation should be avoided"
    severity: error

  view_protocol_error:
    included: ".*ViewOutput.swift|.*ViewInput.swift"
    name: "Property in view protocol"
    regex: " var "
    message: "View protocol should contains only methods"
    severity: error

  router_protocol_error:
    included: ".*RouterInput.swift"
    name: "View in Router protocol"
    regex: "view|View"
    message: "Router protocol methods should contains `Module` instead `View`"
    severity: error

  open_iboutlets:
    included: ".*.swift"
    name: "IBOutlet opening"
    regex: "@IBOutlet ?(weak){0,1} var"
    message: "IBOutlet should be private or fileprivate"
    severity: error

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
# force_cast: warning # implicitly
# force_try:
#   severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
# line_length: 110
# # they can set both implicitly with an array
# type_body_length:
#   - 300 # warning
#   - 400 # error
# # or they can set both explicitly
# file_length:
#   warning: 500
#   error: 1200
# # naming rules can set warnings/errors for min_length and max_length
# # additionally they can set excluded names
# type_name:
#   min_length: 4 # only warning
#   max_length: # warning and error
#     warning: 40
#     error: 50
#   excluded: iPhone # excluded via string
# variable_name:
#   min_length: # only min_length
#     error: 4 # only error
#   excluded: # excluded via string array
#     - id
#     - URL
#     - GlobalAPIKey
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit)